// web-demo-angular/src/layout/footer/footer.component.ts
import { Component } from '@angular/core';
import {MatChipTrailingIcon} from "@angular/material/chips";
import {MatIconModule} from "@angular/material/icon";

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [
    MatChipTrailingIcon,
    MatIconModule,
  ],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent {

}

<div class="footer-main-container">
  <div class="text-container">
    <h2 class="text-title">Welcome to our website.</h2>
    <p class="text-content">We're delighted to have you here and can't wait to share our work with you.</p>
  </div>
  <div class="icon-container">
    <!-- facebook.component.html -->

<!--    <fa-icon [icon]="['fab', 'facebook-square']"></fa-icon>-->
<!--    <mat-chip-trailing-icon svgIcon="facebook"></mat-chip-trailing-icon>-->
<!--    <mat-chip-trailing-icon svgIcon="twitter"></mat-chip-trailing-icon>-->
<!--    <mat-chip-trailing-icon svgIcon="google"></mat-chip-trailing-icon>-->
<!--    <mat-chip-trailing-icon svgIcon="linkedin"></mat-chip-trailing-icon>-->
<!--    <mat-chip-trailing-icon svgIcon="github"></mat-chip-trailing-icon>-->
  </div>
</div>
<div class="footer-sub-container">
 <p>Coppyright &copy; CodeOpacity. Design by NETHUNT</p>
</div>

// web-demo-react-js/src/component/footer/footer.js
import React from 'react'
import './footer.css'
import { FaFacebookF, FaGithub, FaGoogle, FaLinkedinIn, FaTwitter } from 'react-icons/fa';

function Footer() {
  return (
    <div className='footer-container'>
      <div className='footer-main-container'>
        <div className='text-conterner'>
          <p className='text-title'>Welcome to our website.</p>
          <p className='text-content'>We're delighted to have you here and can't wait to share our work with you.</p>
        </div>
        <div className='icon-container'>
          <FaFacebookF />
          <FaTwitter />
          <FaGoogle />
          <FaLinkedinIn />
          <FaGithub />
        </div>
      </div>
      <div className='footer-sub-container'>
        <p>Coppyright &copy; CodeOpacity. Design by NETHUNT</p>
      </div>
    </div>
  )
}

export default Footer;
