// web-demo-react-js/src/component/header/header.js
import React, { useState } from 'react'
import './header.css'
import { Link } from 'react-router-dom';
import Dropdownclick from '../dropdown/dropdownclick/dropdownclick';
import { FaUser } from 'react-icons/fa';
import { useLocation } from 'react-router-dom';

function Header() {
    const location = useLocation();
    const handleActive = (value) =>{
        if(location.pathname==value){
            return true;
        }else {
            return false
        }
    }
    return (
        <div className='header-container'>
            <div className='logo-container'>
                Logo
            </div>
            <div className='navigate-container'>
                <Link to={'/'} className='navigate' style={{background: handleActive('/')?'rgb(236, 235, 234)':''}}>Home</Link>
                <Link to={'/product'} className='navigate' style={{background: handleActive('/product')?'rgb(236, 235, 234)':''}}>Product</Link>
                <Link to={'/about'} className='navigate' style={{background: handleActive('/about')?'rgb(236, 235, 234)':''}}>About</Link>
                <Link to={'/contact'}  className='navigate' style={{background: handleActive('/contact')?'rgb(236, 235, 234)':''}}>Contact</Link>

                <div className='user-button'>
                    <Dropdownclick title={userImage} content={content} position={"-80px"}></Dropdownclick>
                </div>
            </div>
        </div>
    )
}

export default Header;

const title = <FaUser size="32px" className='user-image'/>;
const content = <><li><Link to={'/profile'} style={{ textDecoration: "none", color: "black"}}>Profile</Link></li>  <li><Link style={{ textDecoration: "none", color: "black" }}>Logout</Link></li></>
const userImage = <img src='https://sm.ign.com/t/ign_nordic/cover/a/avatar-gen/avatar-generations_prsz.300.jpg'className='user-image'/>;

// web-demo-angular/src/layout/header/header.component.ts
import {Component, OnInit} from '@angular/core';
import {RouterLink} from "@angular/router";
import {MatMenuModule} from '@angular/material/menu';
import {MatButtonModule} from '@angular/material/button';
import { Router, NavigationEnd } from '@angular/router';
import {CommonModule} from "@angular/common";

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [
    RouterLink,
    MatMenuModule,
    MatButtonModule,
    CommonModule,
  ],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent{
  currentRoute: string = '';

  constructor(private router: Router) {
    this.router.events.subscribe(event => {
      if (event instanceof NavigationEnd) {
        this.currentRoute = event.url;
        console.log(this.currentRoute)
      }
    });
  }
}

<div class="header-container">
  <div class="logo-container">
    Logo
  </div>
  <div class="navigate-container">
    <a routerLink="/" [ngClass]="['navigate', currentRoute=='/' ? 'active-link' : '']"> Home</a>
    <a routerLink="/product" [ngClass]="['navigate', currentRoute=='/product' ? 'active-link' : '']">Product</a>
    <a routerLink="/service" [ngClass]="['navigate', currentRoute=='/service' ? 'active-link' : '']">Service</a>
    <a routerLink="/about" [ngClass]="['navigate', currentRoute=='/about' ? 'active-link' : '']">About</a>
    <div class="user-menu">
      <button [matMenuTriggerFor]="menu">
        <img src="https://sm.ign.com/t/ign_nordic/cover/a/avatar-gen/avatar-generations_prsz.300.jpg" />
      </button>
      <mat-menu #menu="matMenu">
        <a mat-menu-item routerLink="/profile">Profile</a>
        <a mat-menu-item>Logout</a>
      </mat-menu>
    </div>
  </div>
</div>
