// web-demo-react-js/src/component/auth/register/register.js
import React, { useState } from 'react'
import '../login/loginForm.css'
import InputCustom from '../../input/input/inputCustom'
import { Link } from 'react-router-dom';

function Register() {
    const [form, setForm] = useState({});

    const handleInput = (name, value) => {
        setForm({ ...form, [name]: value });
    };

    console.log(form);
    return (
        <div className='login-form-container'>
            <p className="login-title">Register</p>
            <form>
                <div className="input-field">
                    <InputCustom type='text' label='Name' onChange={(value) => handleInput('name', value)} name="name" placeholder='Enter name' />
                </div>
                <div className="input-field">
                    <InputCustom type='text' label='Email' onChange={(value) => handleInput('email', value)} name="email" placeholder='Enter email' />
                </div>
                <div className="input-field">
                    <InputCustom type='text' label='Username' onChange={(value) => handleInput('username', value)} name="username" placeholder='Enter username' />
                </div>
                <div className="input-field">
                    <InputCustom type='password' label='Password' onChange={(value) => handleInput('password', value)} name="password" placeholder='Enter password' />
                </div>
                <div className="input-field">
                    <InputCustom type='password' label='Re-password' onChange={(value) => handleInput('repassword', value)} name="repassword" placeholder='Enter re-password' />
                </div>
            </form>
            <div className="input-field">
                <button className='button' type='button'>Register</button>
            </div>
            <div className="input-field">
                <Link to="/auth/login" className='link-text-new-account'>I already have an account</Link>
            </div>

        </div>
    )
}

export default Register

// web-demo-angular/src/app/auth/register/register.component.ts
import { Component } from '@angular/core';
import {FormControl, FormGroup, FormsModule, ReactiveFormsModule} from "@angular/forms";
import {MatCard, MatCardContent, MatCardFooter, MatCardHeader, MatCardTitle} from "@angular/material/card";
import {MatFormField, MatLabel, MatSuffix} from "@angular/material/form-field";
import {MatIcon} from "@angular/material/icon";
import {MatInput} from "@angular/material/input";
import {RouterLink} from "@angular/router";
import {MatButton} from "@angular/material/button";

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    FormsModule,
    MatCard,
    MatCardContent,
    MatCardHeader,
    MatCardTitle,
    MatFormField,
    MatIcon,
    MatInput,
    MatLabel,
    MatSuffix,
    ReactiveFormsModule,
    RouterLink,
    MatCardFooter,
    MatButton
  ],
  templateUrl: './register.component.html',
  styleUrl: './register.component.css'
})
export class RegisterComponent {
  registerForm = new FormGroup({
    name: new FormControl(''),
    username: new FormControl(''),
    email: new FormControl(''),
    password: new FormControl(''),
    repassword: new FormControl(''),
  })
  hidePassword=true;

  handleSubmit() {

  }

  togglePasswordVisibility(): void {
    this.hidePassword = !this.hidePassword;
  }
}

<div class="login-container">
  <mat-card>
    <mat-card-header>
      <mat-card-title>
        <p>Register</p>
      </mat-card-title>
    </mat-card-header>
    <mat-card-content>
      <form [formGroup]="registerForm" (ngSubmit)="handleSubmit()">
        <mat-form-field appearance="outline" floatLabel="always">
          <mat-label>Name</mat-label>
          <input matInput formControlName="name" type="text" placeholder="Enter your name">
        </mat-form-field>

        <mat-form-field appearance="outline" floatLabel="always">
          <mat-label>Username</mat-label>
          <input matInput formControlName="username" type="text" placeholder="Enter your username">
        </mat-form-field>

        <mat-form-field appearance="outline" floatLabel="always">
          <mat-label>Email</mat-label>
          <input matInput formControlName="email" type="text" placeholder="Enter your email">
        </mat-form-field>

        <mat-form-field appearance="outline" floatLabel="always">
          <mat-label>Password</mat-label>
          <input matInput formControlName="password" [type]="hidePassword ? 'password' : 'text'" placeholder="Enter your password">
          <button mat-icon-button matSuffix (click)="togglePasswordVisibility()" class="button-icon-password">
            <mat-icon>{{ hidePassword ? 'visibility_off' : 'visibility' }}</mat-icon>
          </button>
        </mat-form-field>
        <mat-form-field appearance="outline" floatLabel="always">
          <mat-label>Re password</mat-label>
          <input matInput formControlName="repassword" [type]="hidePassword ? 'password' : 'text'" placeholder="Enter your re password">
          <button mat-icon-button matSuffix (click)="togglePasswordVisibility()" class="button-icon-password">
            <mat-icon>{{ hidePassword ? 'visibility_off' : 'visibility' }}</mat-icon>
          </button>
        </mat-form-field>
        <p class="button-register-container">
          <button mat-raised-button color="primary" type="submit">Register</button>
        </p>
      </form>
      <p class="link-register-container"><a routerLink="/auth/login">I already have an account</a></p>
    </mat-card-content>
  </mat-card>
</div>
